export const products = [
  {
    id: "1",
    name: "Crimson Demon Overlord",
    price: 899.99,
    image: "/fire_sword.png",
    category: "Mythical Heroes",
    isLimited: true,
  },
  {
    id: "2",
    name: "Ronin of the Blood Moon",
    price: 649.99,
    image: "/lightning_ninja.png",
    category: "Elite Swordsmen",
    isLimited: false,
  },
  {
    id: "3",
    name: "Golden Vanguard Paladin",
    price: 1299.99,
    image: "/water_dragon.png",
    category: "Collector Exclusives",
    isLimited: true,
  },
  {
    id: "4",
    name: "Shadow Assassin Zero",
    price: 799.99,
    image: "/shadow_assassin.png",
    category: "Elite Swordsmen",
    isLimited: true,
  },
  {
    id: "5",
    name: "Celestial Dragon Knight",
    price: 1499.99,
    image: "/elite_samurai.png",
    category: "Mythical Heroes",
    isLimited: true,
  },
  {
    id: "6",
    name: "Infernal Blade Master",
    price: 999.99,
    image: "/fire_sword.png",
    category: "Elite Swordsmen",
    isLimited: true,
  },
  {
    id: "7",
    name: "Azure Storm Samurai",
    price: 849.99,
    image: "/lightning_ninja.png",
    category: "Mythical Heroes",
    isLimited: true,
  },
  {
    id: "8",
    name: "Obsidian Warlord",
    price: 1899.99,
    image: "/water_dragon.png",
    category: "Collector Exclusives",
    isLimited: true,
  },
  { id: "f1", name: "Lightning Flash Zenitsu", price: 349.99, image: "/shadow_assassin.png", category: "Elite Swordsmen", isLimited: false },
  { id: "f2", name: "Beast Breath Inosuke", price: 329.99, image: "/elite_samurai.png", category: "Elite Swordsmen", isLimited: false },
  { id: "f3", name: "Water Hashira Giyu", price: 449.99, image: "/fire_sword.png", category: "Elite Swordsmen", isLimited: false },
  { id: "f4", name: "Flame Hashira Rengoku", price: 499.99, image: "/lightning_ninja.png", category: "Mythical Heroes", isLimited: false },
  { id: "f5", name: "Sound Hashira Tengen", price: 429.99, image: "/water_dragon.png", category: "Elite Swordsmen", isLimited: false },
  { id: "f6", name: "Insect Hashira Shinobu", price: 389.99, image: "/shadow_assassin.png", category: "Mythical Heroes", isLimited: false },
  { id: "f7", name: "Mist Hashira Muichiro", price: 419.99, image: "/elite_samurai.png", category: "Elite Swordsmen", isLimited: false },
  { id: "f8", name: "Love Hashira Mitsuri", price: 399.99, image: "/fire_sword.png", category: "Mythical Heroes", isLimited: false },
  { id: "f9", name: "Serpent Hashira Obanai", price: 409.99, image: "/lightning_ninja.png", category: "Elite Swordsmen", isLimited: false },
  { id: "f10", name: "Wind Hashira Sanemi", price: 439.99, image: "/water_dragon.png", category: "Elite Swordsmen", isLimited: false },
  { id: "f11", name: "Stone Hashira Gyomei", price: 549.99, image: "/shadow_assassin.png", category: "Mythical Heroes", isLimited: false },
  { id: "f12", name: "Upper Moon Three Akaza", price: 599.99, image: "/elite_samurai.png", category: "Mythical Heroes", isLimited: false },
  { id: "f13", name: "Upper Moon Two Doma", price: 629.99, image: "/fire_sword.png", category: "Mythical Heroes", isLimited: false },
  { id: "f14", name: "Upper Moon One Kokushibo", price: 699.99, image: "/lightning_ninja.png", category: "Mythical Heroes", isLimited: false },
  { id: "f15", name: "Demon King Muzan", price: 799.99, image: "/water_dragon.png", category: "Collector Exclusives", isLimited: false },
  { id: "f16", name: "Sun Breathing Tanjiro", price: 459.99, image: "/shadow_assassin.png", category: "Elite Swordsmen", isLimited: false },
  { id: "f17", name: "Awakened Nezuko", price: 379.99, image: "/elite_samurai.png", category: "Mythical Heroes", isLimited: false },
  { id: "f18", name: "Hinokami Kagura Dance", price: 899.99, image: "/fire_sword.png", category: "Collector Exclusives", isLimited: false },
  { id: "f19", name: "Thunder God Descent", price: 849.99, image: "/lightning_ninja.png", category: "Collector Exclusives", isLimited: false },
  { id: "f20", name: "Water Dragon Form", price: 749.99, image: "/water_dragon.png", category: "Mythical Heroes", isLimited: false }
];
