export const products = [
  {
    id: "1",
    name: "Crimson Demon Overlord",
    price: 899.99,
    image: "/demon.png",
    category: "Mythical Heroes",
    isLimited: true,
  },
  {
    id: "2",
    name: "Ronin of the Blood Moon",
    price: 649.99,
    image: "/swordsman.png",
    category: "Elite Swordsmen",
    isLimited: false,
  },
  {
    id: "3",
    name: "Golden Vanguard Paladin",
    price: 1299.99,
    image: "/warrior.png",
    category: "Collector Exclusives",
    isLimited: true,
  },
  {
    id: "4",
    name: "Shadow Assassin Zero",
    price: 799.99,
    image: "/swordsman.png",
    category: "Elite Swordsmen",
    isLimited: true,
  },
  {
    id: "5",
    name: "Celestial Dragon Knight",
    price: 1499.99,
    image: "/warrior.png",
    category: "Mythical Heroes",
    isLimited: true,
  },
  {
    id: "6",
    name: "Infernal Blade Master",
    price: 999.99,
    image: "/demon.png",
    category: "Elite Swordsmen",
    isLimited: true,
  },
  {
    id: "7",
    name: "Azure Storm Samurai",
    price: 849.99,
    image: "/swordsman.png",
    category: "Mythical Heroes",
    isLimited: true,
  },
  {
    id: "8",
    name: "Obsidian Warlord",
    price: 1899.99,
    image: "/warrior.png",
    category: "Collector Exclusives",
    isLimited: true,
  }
];
